Learn:
  keep_prob : 0.9
  learning_rate : 0.9
  number_of_total_game: 1130
  batch_size: 32
  max_seq_length: 10

Arch:
  CVRNN:
    hidden_dim : 256
    latent_dim : 256
    x_dim : 33
    y_dim : 56 # tmp value, to be fixed as real data
    z_dim : 256