Learn:
  keep_prob : 0.9
  learning_rate : 0.9
  number_of_total_game: 1130
  batch_size: 32
  max_seq_length: 10
  save_mother_dir: "/cs"
  feature_type: "V1"
  iterate_num: 30
  model_type: 'normal'
  number_of_total_game: 1202

Arch:
  CVRNN:
    hidden_dim : 256
    latent_dim : 256
    x_dim : 33
    y_dim : 43 # 12+31
    z_dim : 256