Learn:
  keep_prob : 0.9
  learning_rate : 0.0001
  number_of_total_game: 1130
  feature_type: "V1"
  batch_size: 32
  iterate_num: 5
  model_type: 'normal'
  apply_box_score: False
  save_mother_dir: "/Local-Scratch"
  data_name: 'ice_hockey-2019'
  predict_target : 'PlayerLocalId'
  player_Id_style: 'PlayerId'
  position_max_length : 15
  apply_stochastic: True
  apply_box_score: False
  gamma : 1
  max_seq_length: 1
  integral_update_flag: True
Arch:
  CVAE:
    n_hidden: 256
    latent_dim: 128
    x_dim : 150 # playerId dimension
    y_dim : 70 # 12state+27action+31team
  Sarsa:
    layer_num: 2
    n_hidden: 256
    output_node: 3
  ScoreDiff:
    layer_num: 2
    n_hidden: 256
    output_node: 3
  Predict:
    layer_num: 2
    n_hidden: 256
    output_node: 2
    predict_target: 'ActionGoal'