Learn:
  keep_prob : 0.9
  learning_rate : 0.0001
  number_of_total_game: 1130
  batch_size: 32
  max_seq_length: 10
  save_mother_dir: "/Local-Scratch"
  feature_type: "V1"
  iterate_num: 30
  model_type: 'normal'
  number_of_total_game: 1202
  action_number : 33
  predict_target: 'PlayerPositionCluster'
  gamma : 1
  player_cluster_number: 26
  data_name: ice_hockey-2019
  sport : 'Ice-Hockey'

Arch:
  CVRNN:
    hidden_dim : 512
    latent_dim : 128
    x_dim : 26
    y_dim : 45 # 33(action)+12
  SARSA:
    lstm_layer_num : 2
    h_size : 256
    dense_layer_number : 2
    dense_layer_size : 256